"""
AATAS — Seed Training Data
~120 hand-labelled command examples to bootstrap the intent classifier.
These cover every intent in natural, varied language.
The more you train via /train 24426, the smarter AATAS gets beyond these.
"""

SEED_DATA = [
    # ── fetch_inbox ──────────────────────────────────────────
    ("show my inbox", "fetch_inbox"),
    ("show inbox", "fetch_inbox"),
    ("check my emails", "fetch_inbox"),
    ("what emails do i have", "fetch_inbox"),
    ("list my emails", "fetch_inbox"),
    ("get my emails", "fetch_inbox"),
    ("fetch inbox", "fetch_inbox"),
    ("what's in my inbox", "fetch_inbox"),
    ("whats in my inbox", "fetch_inbox"),
    ("show me my emails", "fetch_inbox"),
    ("new emails", "fetch_inbox"),
    ("read my emails", "fetch_inbox"),
    ("load inbox", "fetch_inbox"),
    ("pull up inbox", "fetch_inbox"),
    ("check inbox", "fetch_inbox"),
    ("any new emails", "fetch_inbox"),

    # ── fetch_priority ───────────────────────────────────────
    ("show urgent emails", "fetch_priority"),
    ("what's important", "fetch_priority"),
    ("priority inbox", "fetch_priority"),
    ("show me important emails", "fetch_priority"),
    ("sort by priority", "fetch_priority"),
    ("what needs my attention", "fetch_priority"),
    ("urgent emails", "fetch_priority"),
    ("rank my emails", "fetch_priority"),
    ("show emails by priority", "fetch_priority"),
    ("what are my most important emails", "fetch_priority"),
    ("critical emails", "fetch_priority"),
    ("high priority", "fetch_priority"),
    ("priority emails", "fetch_priority"),
    ("what should i deal with first", "fetch_priority"),

    # ── analyse ──────────────────────────────────────────────
    ("analyse email 1", "analyse"),
    ("analyse email 2", "analyse"),
    ("analyse email 3", "analyse"),
    ("analyze email 1", "analyse"),
    ("analyze 2", "analyse"),
    ("summarise email 1", "analyse"),
    ("summarize email 3", "analyse"),
    ("what does email 2 say", "analyse"),
    ("tell me about email 1", "analyse"),
    ("read email 3", "analyse"),
    ("open email 2", "analyse"),
    ("analyse 4", "analyse"),
    ("what's in email 1", "analyse"),
    ("break down email 2", "analyse"),
    ("details of email 3", "analyse"),

    # ── archive ──────────────────────────────────────────────
    ("archive email 1", "archive"),
    ("archive email 2", "archive"),
    ("archive 3", "archive"),
    ("archive number 1", "archive"),
    ("move email 2 to archive", "archive"),
    ("put email 1 in archive", "archive"),
    ("get rid of email 3 from inbox", "archive"),
    ("remove email 1 from inbox", "archive"),
    ("file away email 2", "archive"),

    # ── label ────────────────────────────────────────────────
    ("label email 1 as work", "label"),
    ("label email 2 as urgent", "label"),
    ("tag email 3 as important", "label"),
    ("mark email 1 as personal", "label"),
    ("categorise email 2 as school", "label"),
    ("flag email 3 as review", "label"),
    ("label 1 as finance", "label"),
    ("tag 2 as follow up", "label"),
    ("put email 3 under study", "label"),

    # ── trash ────────────────────────────────────────────────
    ("delete email 1", "trash"),
    ("trash email 2", "trash"),
    ("delete 3", "trash"),
    ("trash 1", "trash"),
    ("remove email 2", "trash"),
    ("get rid of email 1", "trash"),
    ("throw away email 3", "trash"),
    ("permanently delete email 2", "trash"),

    # ── reply ────────────────────────────────────────────────
    ("reply to email 1", "reply"),
    ("draft a reply to email 2", "reply"),
    ("write a reply to email 3", "reply"),
    ("reply casually to email 1", "reply"),
    ("draft casual reply to email 2", "reply"),
    ("write professional reply to email 1", "reply"),
    ("respond to email 3", "reply"),
    ("send a reply to email 2", "reply"),
    ("reply formally to email 1", "reply"),
    ("compose reply to email 3", "reply"),

    # ── create_rule ──────────────────────────────────────────
    ("archive all newsletters", "create_rule"),
    ("archive anything about promotions", "create_rule"),
    ("automatically archive marketing emails", "create_rule"),
    ("archive emails about google classroom", "create_rule"),
    ("label emails from boss as important", "create_rule"),
    ("mark emails from school as education", "create_rule"),
    ("archive all promotional emails", "create_rule"),
    ("create a rule to archive newsletters", "create_rule"),
    ("set up rule to label invoices as finance", "create_rule"),
    ("automatically label emails from hr", "create_rule"),
    ("whenever i get emails about sales archive them", "create_rule"),
    ("archive emails containing unsubscribe", "create_rule"),
    ("move all notification emails to archive", "create_rule"),
    ("label all emails from school", "create_rule"),
    ("trash all spam emails automatically", "create_rule"),
    ("always archive emails from noreply", "create_rule"),
    ("auto archive anything with discount in subject", "create_rule"),

    # ── delete_rule ──────────────────────────────────────────
    ("delete rule 1", "delete_rule"),
    ("remove rule 2", "delete_rule"),
    ("disable rule 3", "delete_rule"),
    ("turn off rule 1", "delete_rule"),
    ("stop rule 2", "delete_rule"),
    ("cancel rule 3", "delete_rule"),
    ("delete automation 1", "delete_rule"),

    # ── list_rules ───────────────────────────────────────────
    ("show my rules", "list_rules"),
    ("list my rules", "list_rules"),
    ("what rules do i have", "list_rules"),
    ("show automation rules", "list_rules"),
    ("my automations", "list_rules"),
    ("view rules", "list_rules"),
    ("what automations are active", "list_rules"),
    ("show me my automations", "list_rules"),
    ("what have i set up", "list_rules"),

    # ── list_history ─────────────────────────────────────────
    ("show history", "list_history"),
    ("what have you done", "list_history"),
    ("show action history", "list_history"),
    ("what actions did you take", "list_history"),
    ("recent actions", "list_history"),
    ("show me what you've done", "list_history"),
    ("history", "list_history"),
    ("audit log", "list_history"),
    ("what did aatas do", "list_history"),

    # ── none ─────────────────────────────────────────────────
    ("hello", "none"),
    ("hi", "none"),
    ("hey", "none"),
    ("thanks", "none"),
    ("ok", "none"),
    ("good morning", "none"),
    ("how are you", "none"),
    ("what can you do", "none"),
    ("help me", "none"),
    ("what are you", "none"),
    ("who are you", "none"),
    ("cool", "none"),
    ("nice", "none"),
    ("got it", "none"),
    ("alright", "none"),
]
